env:
  #"node" is the latest version
  - TRAVIS_NODE_VERSION="node"
  - TRAVIS_NODE_VERSION="iojs"
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
os:
  - linux
  - osx
before_install:
  # nvm is not yet supported on osx, manually install
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use --delete-prefix $TRAVIS_NODE_VERSION
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
script: 
  - npm test
after_script:
  - npm run coveralls
services:
  - redis-server